[package]
version = "0.1.0"
name = "guest"
edition = "2021"

[dependencies]
sp1-zkvm = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray = "0.16.0"
csv = "1.1"
alloy-sol-types = "0.7.7"

